export const DEFAULT_THEME = 'g-lawrencium'

const GRADIENT_TOKENS = {
  surface: 'rgba(0,0,0,0.32)',
  card: 'rgba(0,0,0,0.28)',
  tile: 'rgba(255,255,255,0.10)',
  field: 'rgba(0,0,0,0.38)',
  dock: 'rgba(10,10,20,0.55)',
  ink: '#F4F4F6',
  soft: '#FFFFFF',
  sub: '#C6C4D4',
  muted: '#8F8DA0',
  faint: '#A6A4B8',
  line: '#FFFFFF',
  overlay: 'rgba(0,0,0,0.5)',
  ring: 'rgba(255,255,255,0.15)',
}

export const THEMES = [
  {
    id: 'dark',
    name: 'Dark',
    glass: false,
    colors: {
      bg: '#0B0B12',
      bg2: '#131322',
      surface: '#17171F',
      card: '#18181B',
      tile: '#232325',
      field: '#0F0F16',
      dock: '#17171FCC',
      ink: '#F4F4F6',
      soft: '#FCFCFC',
      sub: '#A1A1AA',
      muted: '#6E6E7A',
      faint: '#9C9CA8',
      line: '#FFFFFF',
      overlay: 'rgba(0,0,0,0.6)',
      ring: '#1B1B26',
    },
  },
  {
    id: 'light',
    name: 'Light',
    glass: false,
    colors: {
      bg: '#F2F3F7',
      bg2: '#E6E8F0',
      surface: '#FFFFFF',
      card: '#FFFFFF',
      tile: '#EDEEF4',
      field: '#FFFFFF',
      dock: 'rgba(255,255,255,0.85)',
      ink: '#1B1C24',
      soft: '#0E0F16',
      sub: '#4E515C',
      muted: '#8B8D9A',
      faint: '#767986',
      line: '#000000',
      overlay: 'rgba(0,0,0,0.35)',
      ring: '#E4E6EE',
    },
  },
  {
    id: 'glass',
    name: 'Glass',
    glass: true,
    colors: {
      bg: 'rgba(14,14,26,0.55)',
      bg2: 'rgba(20,18,48,0.55)',
      surface: 'rgba(255,255,255,0.08)',
      card: 'rgba(255,255,255,0.07)',
      tile: 'rgba(255,255,255,0.12)',
      field: 'rgba(0,0,0,0.28)',
      dock: 'rgba(16,16,30,0.55)',
      ink: '#F4F4F6',
      soft: '#FFFFFF',
      sub: '#C6C4D4',
      muted: '#8F8DA0',
      faint: '#A6A4B8',
      line: '#FFFFFF',
      overlay: 'rgba(0,0,0,0.5)',
      ring: 'rgba(255,255,255,0.15)',
    },
  },
  {
    id: 'midnight',
    name: 'Midnight',
    glass: false,
    colors: {
      bg: '#0E0D1C',
      bg2: '#171431',
      surface: '#17142E',
      card: '#1A1733',
      tile: '#262143',
      field: '#0B0A18',
      dock: 'rgba(14,13,28,0.85)',
      ink: '#F1EFFA',
      soft: '#FAF9FF',
      sub: '#B3AECC',
      muted: '#6F6B8C',
      faint: '#9C97B8',
      line: '#FFFFFF',
      overlay: 'rgba(0,0,0,0.6)',
      ring: '#211D40',
    },
  },
  {
    id: 'oled',
    name: 'OLED',
    glass: false,
    colors: {
      bg: '#000000',
      bg2: '#000000',
      surface: '#0A0A0A',
      card: '#0D0D0D',
      tile: '#151515',
      field: '#000000',
      dock: 'rgba(0,0,0,0.9)',
      ink: '#F5F5F5',
      soft: '#FFFFFF',
      sub: '#A8A8A8',
      muted: '#6E6E6E',
      faint: '#9C9C9C',
      line: '#FFFFFF',
      overlay: 'rgba(0,0,0,0.7)',
      ring: '#141414',
    },
  },
  {
    id: 'rose',
    name: 'Rose',
    glass: false,
    colors: {
      bg: '#FDF2F6',
      bg2: '#FBE4ED',
      surface: '#FFFFFF',
      card: '#FFFFFF',
      tile: '#F6E3EA',
      field: '#FFFFFF',
      dock: 'rgba(255,255,255,0.85)',
      ink: '#3A2430',
      soft: '#1F0F17',
      sub: '#8A6474',
      muted: '#B08B9B',
      faint: '#9D7488',
      line: '#000000',
      overlay: 'rgba(0,0,0,0.35)',
      ring: '#F1D9E2',
    },
  },
  // Gradient themes, grouped by hue family — the order here IS the order of
  // the swatch grid in Settings → Appearance. Families follow the accent-color
  // row: amber, green, rose, pink, purple, red, blue.
  // ── amber & gold ────────────────────────────────────────────────────────
  {
    id: 'g-dark-knight',
    name: 'Dark Knight',
    glass: true,
    colors: gradientThemeColors('#BA8B02', '#181818'),
  },
  {
    id: 'g-army',
    name: 'Army',
    glass: true,
    colors: gradientThemeColors('#414D0B', '#727A17'),
  },
  // ── green ───────────────────────────────────────────────────────────────
  {
    id: 'g-moss',
    name: 'Moss',
    glass: true,
    colors: gradientThemeColors('#134E5E', '#71B280'),
  },
  {
    id: 'g-under-the-lake',
    name: 'Under the Lake',
    glass: true,
    colors: gradientThemeColors('#093028', '#237A57'),
  },
  {
    id: 'g-forest',
    name: 'Forest',
    glass: true,
    colors: gradientThemeColors('#5A3F37', '#2C7744'),
  },
  {
    id: 'g-terminal',
    name: 'Terminal',
    glass: true,
    colors: gradientThemeColors('#000000', '#0F9B0F'),
  },
  {
    id: 'g-vine',
    name: 'Vine',
    glass: true,
    colors: gradientThemeColors('#001510', '#00BF8F'),
  },
  // ── rose & wine ─────────────────────────────────────────────────────────
  {
    id: 'g-sweet-morning',
    name: 'Sweet Morning',
    glass: true,
    colors: gradientThemeColors('#FF5F6D', '#FFC371'),
  },
  {
    id: 'g-love-couple',
    name: 'Love Couple',
    glass: true,
    colors: gradientThemeColors('#3A6186', '#89253E'),
  },
  // ── pink & magenta ──────────────────────────────────────────────────────
  {
    id: 'g-purple-love',
    name: 'Purple Love',
    glass: true,
    colors: gradientThemeColors('#CC2B5E', '#753A88'),
  },
  {
    id: 'g-aubergine',
    name: 'Aubergine',
    glass: true,
    colors: gradientThemeColors('#AA076B', '#61045F'),
  },
  {
    id: 'g-flickr',
    name: 'Flickr',
    glass: true,
    colors: gradientThemeColors('#33001B', '#FF0084'),
  },
  {
    id: 'g-vice-city',
    name: 'Vice City',
    glass: true,
    colors: gradientThemeColors('#3494E6', '#EC6EAD'),
  },
  // ── purple & violet ─────────────────────────────────────────────────────
  {
    id: 'g-lawrencium',
    name: 'Lawrencium',
    glass: true,
    colors: gradientThemeColors('#0F0C29', '#24243E', '#302B63'),
  },
  {
    id: 'g-twitch',
    name: 'Twitch',
    glass: true,
    colors: gradientThemeColors('#6441A5', '#2A0845'),
  },
  {
    id: 'g-deep-purple',
    name: 'Deep Purple',
    glass: true,
    colors: gradientThemeColors('#673AB7', '#512DA8'),
  },
  {
    id: 'g-mauve',
    name: 'Mauve',
    glass: true,
    colors: gradientThemeColors('#42275A', '#734B6D'),
  },
  // ── red ─────────────────────────────────────────────────────────────────
  {
    id: 'g-pure-lust',
    name: 'Pure Lust',
    glass: true,
    colors: gradientThemeColors('#333333', '#DD1818'),
  },
  {
    id: 'g-the-strain',
    name: 'The Strain',
    glass: true,
    colors: gradientThemeColors('#870000', '#190A05'),
  },
  {
    id: 'g-namn',
    name: 'Namn',
    glass: true,
    colors: gradientThemeColors('#A73737', '#7A2828'),
  },
  {
    id: 'g-dawn',
    name: 'Dawn',
    glass: true,
    colors: gradientThemeColors('#F3904F', '#3B4371'),
  },
  {
    id: 'g-king-yna',
    name: 'King Yna',
    glass: true,
    colors: gradientThemeColors('#1A2A6C', '#FDBB2D', '#B21F1F'),
  },
  // ── blue & slate ────────────────────────────────────────────────────────
  {
    id: 'g-royal',
    name: 'Royal',
    glass: true,
    colors: gradientThemeColors('#141E30', '#243B55'),
  },
  {
    id: 'g-moonlit-asteroid',
    name: 'Moonlit Asteroid',
    glass: true,
    colors: gradientThemeColors('#0F2027', '#2C5364', '#203A43'),
  },
  {
    id: 'g-frost',
    name: 'Frost',
    glass: true,
    colors: gradientThemeColors('#000428', '#004E92'),
  },
  {
    id: 'g-very-blue',
    name: 'Very Blue',
    glass: true,
    colors: gradientThemeColors('#0575E6', '#021B79'),
  },
  {
    id: 'g-clear-sky',
    name: 'Clear Sky',
    glass: true,
    colors: gradientThemeColors('#005C97', '#363795'),
  },
  {
    id: 'g-sublime-vivid',
    name: 'Sublime Vivid',
    glass: true,
    colors: gradientThemeColors('#FC466B', '#3F5EFB'),
  },
]

export function themeById(id) {
  return THEMES.find((t) => t.id === id) ?? THEMES.find((t) => t.id === DEFAULT_THEME) ?? THEMES[0]
}

function gradientThemeColors(bg, bg2, mid) {
  return { ...GRADIENT_TOKENS, bg, bg2, ...(mid ? { mid } : {}) }
}
